---
title: "main_program"
author: "Dennis Perez"
email: dperez81@ucmerced.edu
output:
  html_document: default
  pdf_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

My son's first line of code:
```{r}

# Benny's first line of code <3: ccx,,c 

```


----Section: Formulating the question----
```{r}

#One may wonder what lead me to conduct this analysis on gender. First and foremost, being a researcher of the original study, I started the analysis of the data with some pre-formed conceptions. Mainly, I knew the original study was mainly concerned with participants ability to detect bias from higher-level groups, like organizations. So, I tried to think of an analysis that would be different from the primary goals of the initial study, but also something that could provide useful information for researchers to consider in future studies. Furthermore, I did not want to work the problem of biased information the same way as the initial study: higher-level groups to smaller individual differences. Instead, I decided to explore a smaller subset of the data that focused on what I call lower-level groups like gender. 

#I felt that gender was a fair compromise since it allowed for a small enough group of participants to consider and still provided individual participant information. I was also considering examining age, ethnicity, and gender together, but again, I felt this would be too similar of an approach of the initial study that worked the problem of bias from a larger group to a smaller group. 


```


----Section: Installing and loading packages----
```{r}
install.packages('tidyverse')
install.packages('knitr')
# install.packages('magrittr')
install.packages('tidylog')
# install.packages('broom')
install.packages('skimr')
# install.packages('ggdist') 

library(tidyverse) 
library(knitr)
# library(magrittr)
library(tidylog)
# library(broom)
library(skimr) 
# library(ggdist) 
#library(tibble) 
library(plotly)
```


----Section: Reading in the data----
```{r}

# Creating a variable to house the copy of the original csv
# Copy of data will be used to preserve original data and make comparisons later

df_copy <- read_csv('data/CopyOfdataset_212.csv')

```

----Section: -Looking at the data---
```{r}
view(df_copy) # Viewing whole dataset
str(df_copy) # Viewing class of vars in dataset
skim(df_copy) # Performs most of the above

```


----Section: Data cleaning----
```{r}  
# ** Please see the associated section of this code within the "Final_Project_Report.docx" for a further explanation of the methods used here.

# Removed import id row (row 1)
# Removed row that had associated survey question (row 2)
# Removed rows for participants who did not complete all of the survey (rows 104-110). 

df_copy <- df_copy[-c(1, 2, 104, 105, 106, 107, 108, 109, 110),]


```



----Section: Data analyzations  (part 1)---
```{r}

# Reading in original variable to new variable to be used for specific manipulations in this section.
df_copy1 = df_copy 

# social_amt _1 - 7
# Recoding hours spent on social media 

# I only wanted a basic sum of the amount of usage for each participant. Thus, I chose not to make direct representation for hours. I just made the numbers to loosely represent a difference in amount for comparison. I realize this may throw off the analysis but I figured that since I made the numbers so small, it wouldn't make too much of a difference.
# 2+ hrs/day : 3 for example, next number is 3 
# 1-2 hrs/day: 2 highest in range is 2
# under 1 hr/day: 1 rounded to 1
# none: 0 none indicates no hours spent 


# How to see the diff types of rows in a column
hello = unique(df_copy1$`social_amt _1`)

# Recoding columns for hours on social media
df_copy1 <- df_copy1 %>%
  mutate_at(.vars = vars('social_amt _1', 'social_amt _2', 'social_amt _3', 'social_amt _4', 'social_amt _5', 'social_amt _6', 'social_amt _7'), .funs = funs(recode(., '2+ hrs/day' = 3, '1-2 hrs/day' = 2, 'under 1 hr/day' = 1, 'none' = 0, .default = NA_real_))) 

# Take the sum of hours spend on all social media for each participant.
socialMediaUsage_sum <- rowSums(df_copy1[, c(56, 57, 58, 59, 60, 61, 62)], na.rm = TRUE)

# Splitting data by gender
splitting_data1 <- strsplit(df_copy1$gender, split = ", ")

# Created a new data frame and column that used the socialMediaUsage_sum output.
new_df1 <- data.frame(socialMediaUsage_sum = rep(socialMediaUsage_sum, sapply(splitting_data1, length)), gender = unlist(splitting_data1))

# dropped any NA values
# grouped to utilize dplyr functions
amount_by_gender1 <- na.omit(new_df1) %>%
  group_by(gender, socialMediaUsage_sum) %>%
  summarise(count = n())

# Renamed columns to be more intuitive to observation I am trying to make
names(amount_by_gender1)[2] <- "SocialMediaUse_sum_perParticipant" 
names(amount_by_gender1)[3] <- "Count"


# Plotting results
ggplot(amount_by_gender1, aes(Count, reorder(gender, SocialMediaUse_sum_perParticipant))) +
  geom_col(aes(fill = SocialMediaUse_sum_perParticipant))  +
  scale_fill_gradient2(low = "#d7191c",
                       high = "#2b83ba",
                       mid = "#ffffbf",
                       midpoint = median(amount_by_gender1$SocialMediaUse_sum_perParticipant))+
  theme(axis.title.y = element_blank(),
        panel.background = element_rect(fill="black"),
        panel.grid = element_line(colour = "#333333"))

```



----Section: Data anaylzations (part 2)----
```{r}
# Going to try to change variables from character to numeric.
# My hope is that it will be easier to make comparisons this way.
# Changing to numeric values to compare gender against how likely they were to fact check information participants came across.
# Resource: https://www.r-bloggers.com/2021/07/point-biserial-correlation-in-r-quick-guide/


df_copy2 = df_copy

# Recoding likelihood to fact check. 
df_copy_recode1 <- df_copy2 %>%
  mutate_at(.vars = vars('fact_online'), .funs = funs(recode(., 'Extremely' = 4, 'Very' = 3, 'Somewhat' = 2, 'A little' = 1, 'Not at all' = 0, .default = NA_real_))) 

# Recoding male or female
df_copy_recode2 <- df_copy2 %>%
  mutate_at(.vars = vars('gender'), .funs = funs(recode(., 'Male' = 0, 'Female' = 1)))

# How likely one is to fact check by gender 
results_Gen_Fact = cor.test(df_copy_recode2$gender, df_copy_recode1$fact_online) 

# Plotting results
# decline to answer only had one so it doesn't populate as normal
# Little dot is an outlier possibly representing arbitrary value
boxplot(fact_online~gender, data = df_copy_recode1)

```


----Section: Data anaylzations (part 3)----
```{r}
# Next, I wanted to see was how often each gender discusses current events or news with family or friends


# Each variable is followed with a 3 to denote it belonging to part 3
df_copy3 = df_copy 

# Split by gender
splitting_data3 <- strsplit(df_copy3$gender, split = ", ")

# Create new dataframe to create new column that replicates the discuss column and associates with new split
new_df3 <- data.frame(discuss = rep(df_copy3$discuss, sapply(splitting_data3, length)), gender = unlist(splitting_data3))


# Attempted to delete the arbitrary value of -99, but failed and not sure why.
# Dropped NA values
# Grouped cols to utilize summarize and count functions

# amount_by_gender3 <- df_copy3 %>%
#   subset(discuss!="99") %>%
#   na.omit(new_df3) %>%
#   group_by(gender, discuss) %>%
#   summarise(count = n())

amount_by_gender3 <- na.omit(new_df3) %>%
  group_by(gender, discuss) %>%
  summarise(count = n())


# Renamed columns to be more intuitive to observation I am trying to make
names(amount_by_gender3)[2] <- "Yes_or_No"
names(amount_by_gender3)[3] <- "Count"


# Plotting
gender_discuss_plt3 <- ggplot(amount_by_gender3, aes(Yes_or_No, Count, colour=gender))+
  geom_point(size=5)+
  xlab('Discusses current events') +
  ylab('Amount') +
  ggtitle('Whether or not each gender discusses current events')

ggplotly(gender_discuss_plt3, dynamicTicks = T)


```












































































